### ISSUE TITLE
Session data not being removed

### ISSUE THREAD

**Issue by pascalallen** [icza/session#4] opened 2016-12-27 15:59 UTC
I have a logout function which uses `session.Remove(sess, res)` BUT I don't believe that it is completely removing the session data because I am still able to view session data(via a user edit page which displays a logged in users data) after that function is called. Also, when a session is started I see `Session added...` in my terminal. Is there supposed to be a similar message for when a session ends(`Session ended...`)? Thank you.

If you have a moment, here is a link to my code:

https://github.com/pascalallen/Go-db/blob/master/db.go

**Comment by icza** [comment] 2016-12-27 17:19
The in-memory store also prints a log message when a session is removed, you can check this in [inmem_store.go](https://github.com/icza/session/blob/master/inmem_store.go), `Remove()` method.

If no `"Session removed..."` message is printed for you, that means the `Remove()` method is never called, which in your code means the `Session` returned by `session.Get()` returns `nil`. Print it to verify.

**Comment by pascalallen** [comment] 2016-12-27 17:27
So should I not have `if sess != nil`?

**Comment by icza** [comment] 2016-12-27 17:30
No, you can only call methods on `sess` if it's not `nil`. I'm saying you don't see a `"Session removed..."` message because most likely your `sess` is `nil`. Which means you don't have a session at that point. Please print the `sess` variable to confirm.

**Comment by pascalallen** [comment] 2016-12-27 17:36
When I try to print `sess` in my logOut function it isn't printing anything. I'm grabbing the current session like this: `sess := session.Get(req)`

**Comment by icza** [comment] 2016-12-27 17:47
Print it like this:

    sess := session.Get(req)
    log.Println("Session:", sess)

If you don't see anything printed, that means your `logOut()` handler function is not even called.

**Comment by pascalallen** [comment] 2016-12-27 17:57
That's what I have, and I'm confused as to why it isn't being called because it takes a request from a logout button. Why wouldn't it be called?

**Comment by icza** [comment] 2016-12-27 18:02
I don't know. Try calling the logout URL manually, e.g. in a new browser tab enter:

    http://localhost:8080/logout

...and see if your handler gets called.

**Comment by pascalallen** [comment] 2016-12-27 18:15
It still isn't getting called. Could it have something to do with `session.Global.Close()
    session.Global = session.NewCookieManagerOptions(session.NewInMemStore(), &session.CookieMngrOptions{AllowHTTP: true})` being before the handlers inside the main function?

**Comment by icza** [comment] 2016-12-27 18:19
If I understand it right, we are not talking about session removal not being called, but your basic HTTP handler. Put a log message to the beginning of `logOut()` to see. If your HTTP handler doesn't get called, the issue is not related to session management.

**Comment by pascalallen** [comment] 2016-12-27 18:27
You're right. The function isn't even being called and i have no idea why.

**Comment by icza** [comment] 2016-12-27 21:06
First try to call it with any HTTP client, e.g. `curl`. If that triggers `logOut()`, then the bug is in your client side web document. In that case try to debug in your browser (e.g. Developer console in Chrome). If that does not trigger your `logOut()`, then it's your HTTP server configuration issue (routing table, path etc.).

Anyway, since this is not session management related, closing the issue.

**Closed as completed by icza** 2016-12-27 21:06 UTC
Labels: invalid

**Comment by rustamin** [comment] 2017-10-03 00:58
it happend to me too, 2 days only working with session. fuck

**Comment by icza** [comment] 2017-10-03 11:30
And how would I be able to assist without any details / code?
